# Generated by Django 5.0.6 on 2024-05-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_goaloftheday_fluiddram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='food/')),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Начинающий', 'Easy'), ('Средний', 'Medium'), ('Продвинутый', 'Hard')], default='Начинающий', max_length=100)),
                ('time', models.IntegerField()),
                ('IsPopular', models.CharField(choices=[('Начинающий', 'Easy'), ('Средний', 'Medium'), ('Продвинутый', 'Hard')], default='Начинающий', max_length=20)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='exerciseID',
        ),
        migrations.AddField(
            model_name='plan',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exercise'),
        ),
        migrations.AddField(
            model_name='plan',
            name='modelType',
            field=models.CharField(choices=[('Exercise', 'Exercise'), ('Food', 'Food')], default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Начинающий', 'Easy'), ('Средний', 'Medium'), ('Продвинутый', 'Hard')], default='Начинающий', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.food'),
        ),
        migrations.CreateModel(
            name='Nutrion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammes', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='recipe/')),
                ('grammes', models.FloatField()),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food')),
            ],
        ),
    ]
