# Generated by Django 5.0.6 on 2024-05-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_food_remove_plan_exerciseid_plan_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='exercise',
            new_name='exerciseID',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='food',
            new_name='foodID',
        ),
    ]
